#!/bin/sh

set -e

dpkg-maintscript-helper mv_conffile /opt/kaltura/app/configurations/php/conf.d/10-mysqlnd.ini /opt/kaltura/app/configurations/php/mods-available/mysqlnd.ini 7.0.0-1 -- "$@";


for dsoname in mysqlnd mysqli pdo_mysql ; do
    inifile=${dsoname}.ini

    dpkg-maintscript-helper mv_conffile /opt/kaltura/app/configurations/php/conf.d/${inifile} /opt/kaltura/app/configurations/php/mods-available/${inifile} 7.0.0-1 -- "$@";
done

exit 0
