#!/bin/sh

set -e



for dsoname in pgsql pdo_pgsql ; do
    inifile=${dsoname}.ini

    dpkg-maintscript-helper mv_conffile /opt/kaltura/app/configurations/php/conf.d/${inifile} /opt/kaltura/app/configurations/php/mods-available/${inifile} 7.0.0-1 -- "$@";
done

exit 0
