#!/bin/sh
if [ "$1" = "configure" ];then
        ALERTMANAGER_MAIN_CONF=/opt/kaltura/prometheus/alertmanager/etc/alertmanager.yml
        . /usr/share/debconf/confmodule
        db_get 'kaltura-alertmanager/smtp_host'
        if [ -z "$RET" ];then
                db_set 'kaltura-alertmanager/smtp_host' "localhost:25"
        fi
        db_input critical 'kaltura-alertmanager/smtp_host' || true
        db_go || true
        db_get 'kaltura-alertmanager/smtp_host'
        SMTP_HOST=$RET
        db_input critical 'kaltura-alertmanager/smtp_user' || true
        db_go || true
        db_get 'kaltura-alertmanager/smtp_user'
        SMTP_USER=$RET

        if [ -n "$SMTP_USER" ];then
                db_input critical 'kaltura-alertmanager/smtp_passwd' || true
                db_go || true
                db_get 'kaltura-alertmanager/smtp_passwd'
                SMTP_PASSWD=$RET
        fi
        db_get 'kaltura-alertmanager/from_addr'
        db_input critical 'kaltura-alertmanager/from_addr' || true
        db_go || true
        db_get 'kaltura-alertmanager/from_addr'
        FROM_EMAIL=$RET

        db_get 'kaltura-alertmanager/default_alerting_email_addr'
        db_input critical 'kaltura-alertmanager/default_alerting_email_addr' || true
        db_go || true
        db_get 'kaltura-alertmanager/default_alerting_email_addr'
        DEFAULT_ALERTING_EMAIL_ADDR=$RET

        sed -i -e "s^@SMTP_HOST@^$SMTP_HOST^g" -e "s^@FROM_EMAIL@^$FROM_EMAIL^g" -e "s^@DEFAULT_ALERTING_EMAIL_ADDR@^$DEFAULT_ALERTING_EMAIL_ADDR^g" $ALERTMANAGER_MAIN_CONF
        if [ -n "$SMTP_USER" ];then
                sed -i "s/^\(\s*#smtp_auth_username:\)\s*'@SMTP_USER@'/\1 '$SMTP_USER'/" $ALERTMANAGER_MAIN_CONF
        fi

        if [ -n "$SMTP_PASSWD" ];then
                sed -i "s/^\(\s*#smtp_auth_password:\)\s*'@SMTP_PASSWD@'/\1 '$SMTP_PASSWD'/" $ALERTMANAGER_MAIN_CONF
        fi
fi
chown prometheus.prometheus /opt/kaltura/prometheus/alertmanager/data /opt/kaltura/log/alertmanager /opt/kaltura/var/run/alertmanager

#DEBHELPER#
