#!/bin/bash
enable_apps_conf()
{
	for CONF in  /opt/kaltura/app/configurations/apache/conf.d/apps.conf /opt/kaltura/app/configurations/apache/conf.d/var.conf ;do
		ln -sf $CONF /etc/apache2/sites-available/
		a2ensite `basename $CONF`
	done
}
enable_admin_conf()
{
	ln -sf /opt/kaltura/app/configurations/apache/conf.d/admin.conf /etc/apache2/sites-available/
	a2ensite admin.conf
}

KALTURA_FUNCTIONS_RC=/opt/kaltura/bin/kaltura-functions.rc
if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
        OUT="${BRIGHT_RED}ERROR:could not find $KALTURA_FUNCTIONS_RC so, exiting..${NORMAL}"
        echo -en $OUT
        exit 3
fi

RC_FILE=/etc/kaltura.d/system.ini
if [ ! -r "$RC_FILE" ];then
	echo -e "${BRIGHT_RED}ERROR: could not find $RC_FILE so, exiting..${NORMAL}"
	exit 1 
fi
. $RC_FILE


. $KALTURA_FUNCTIONS_RC
KALTURA_PREFIX=/opt/kaltura
APP_DIR=/opt/kaltura/app
KALTURA_GROUP=kaltura
KALTURA_USER=kaltura
APACHE_USER=www-data
APACHE_GROUP=www-data

for i in filter expires headers proxy rewrite;do
	OUT=`a2enmod $i`
done
KALTURA_VERSION="`dpkg-query -W -f'${Version}' kaltura-base|awk -F "+" '{print $1}'`"
. /usr/share/debconf/confmodule

chown -R $KALTURA_USER:$APACHE_GROUP $KALTURA_PREFIX/log 
chown -R $KALTURA_USER:$APACHE_GROUP $KALTURA_PREFIX/tmp 
chown -R $KALTURA_USER:$APACHE_GROUP $KALTURA_PREFIX/app/cache 
chmod -R 775 $KALTURA_PREFIX/log $KALTURA_PREFIX/tmp $KALTURA_PREFIX/app/cache $KALTURA_PREFIX/web

# handle the zz_kaltura*.ini
if [ "$1" = "configure" ]; then
	#update-rc.d memcache defaults
	trap 'my_trap_handler "${LINENO}" ${$?}' ERR
	send_install_becon `basename $0` $ZONE install_start 0 
	KALTURA_APACHE_CONF=$APP_DIR/configurations/apache
	KALTURA_APACHE_CONFD=$KALTURA_APACHE_CONF/conf.d
	db_input critical kaltura-front/is_apache_ssl || true
	db_go || true
	db_get kaltura-front/is_apache_ssl
	IS_SSL="$RET"
	if [ "$IS_SSL" != 'true' ];then
		trap - ERR
		echo "use kaltura" | mysql -h$DB1_HOST -u$DB1_USER -p$DB1_PASS -P$DB1_PORT $DB1_NAME 2> /dev/null
		if [ $? -eq 0 ];then
			echo "update permission set STATUS=3 WHERE permission.NAME='FEATURE_KMC_ENFORCE_HTTPS' ;" | mysql $DB1_NAME -h$DB1_HOST -u$DB1_USER -P$DB1_PORT -p$DB1_PASS 2> /dev/null 
		fi
		trap 'my_trap_handler "${LINENO}" ${$?}' ERR
		MAIN_APACHE_CONF=$KALTURA_APACHE_CONF/kaltura.conf
	else
			a2enmod ssl
			# configure SSL:
			MAIN_APACHE_CONF=$KALTURA_APACHE_CONF/kaltura.ssl.conf
			#db_get kaltura-front/apache_ssl_cert
			db_input critical kaltura-front/apache_ssl_cert || true
			db_go || true
			db_get kaltura-front/apache_ssl_cert
			CRT_FILE=$RET

			db_input critical kaltura-front/apache_ssl_key || true
			db_go || true
			db_get kaltura-front/apache_ssl_key
			KEY_FILE=$RET

			db_input critical kaltura-front/apache_ssl_chain || true
			db_go || true
			db_get kaltura-front/apache_ssl_chain
			CHAIN_FILE=$RET
			#if [ -z "$CA_FILE" ];then
			#	echo -e "${CYAN}Please input path to your SSL CA file or leave empty in case you have none${CYAN}:${NORMAL}"
			#	read -e CA_FILE
			#fi
			# check key and crt match
			CRT_SUM=`openssl x509 -in $CRT_FILE -modulus -noout | openssl md5`
			KEY_SUM=`openssl rsa -in $KEY_FILE -modulus -noout | openssl md5`
			if [ "$CRT_SUM" != "$KEY_SUM" ];then
				echo -e ${BRIGHT_RED}"

			ERROR: MD5 sums between .key and .crt files DO NOT MATCH
			# openssl rsa -in $KEY_PATH -modulus -noout | openssl md5
			$KEY_HASH
			# openssl x509 -in $CERT_PATH -modulus -noout | openssl md5
			$CRT_HASH
			${NORMAL}
			"
				exit 3
			fi
			# it might fail if done before there's a DB but I don't want it to stop the config script, it can be easily fixed later.
			php $APP_DIR/deployment/base/scripts/insertPermissions.php -d $APP_DIR/deployment/permissions/ssl/ >/dev/null 2>&1 ||true

			# if cert is self signed:
			if openssl verify  $CRT_FILE | grep 'self signed certificate' -q ;then

				db_input critical kaltura-front/self_signed_cert || true
				db_go || true
				db_get kaltura-front/self_signed_cert

				echo -e "settings.clientConfig.verifySSL=0" >> $APP_DIR/configurations/admin.ini
				sed -i  's@\(\[production\]\)@\1\nsettings.clientConfig.verifySSL=0@' $APP_DIR/configurations/admin.ini
			fi
			sed "s#@SSL_CERTIFICATE_FILE@#$CRT_FILE#g" -i $MAIN_APACHE_CONF
			echo "@@@@@@@2$KEY_FILE@@@@@@@@@@@2"
			sed -i "s#@SSL_CERTIFICATE_KEY_FILE@#$KEY_FILE#g" $MAIN_APACHE_CONF
			if [ -r "$CHAIN_FILE" ];then
				sed -i "s^SSLCertificateChainFile @SSL_CERTIFICATE_CHAIN_FILE@^SSLCertificateChainFile $CHAIN_FILE^" $MAIN_APACHE_CONF
			else
				CHAIN_FILE="NO_CHAIN"
				sed -i "s^SSLCertificateChainFile @SSL_CERTIFICATE_CHAIN_FILE@^#SSLCertificateChainFile @SSL_CERTIFICATE_CHAIN_FILE@^" $MAIN_APACHE_CONF
			fi
			if [ -r "$CA_FILE" ];then
				sed -i "s^SSLCACertificateFile @SSL_CERTIFICATE_CA_FILE@^SSLCACertificateFile $CA_FILE^" $MAIN_APACHE_CONF
			else
				CA_FILE="NO_CA"
				sed -i "s^SSLCACertificateFile @SSL_CERTIFICATE_CA_FILE@^#SSLCACertificateFile @SSL_CERTIFICATE_CA_FILE@^" $MAIN_APACHE_CONF
			fi
			echo "CRT_FILE=$CRT_FILE" >> $RC_FILE
			echo "KEY_FILE=$KEY_FILE" >> $RC_FILE
			echo "CA_FILE=$CA_FILE" >> $RC_FILE
			echo "CHAIN_FILE=$CHAIN_FILE" >> $RC_FILE

		fi

	if [ "$IS_SSL" = 'true' ];then
		DEFAULT_PORT=443
		trap - ERR
		echo "use kaltura" | mysql -h$DB1_HOST -u$DB1_USER -p$DB1_PASS -P$DB1_PORT $DB1_NAME 2> /dev/null
		if [ $? -eq 0 ];then
			echo "update permission set STATUS=1 WHERE permission.PARTNER_ID IN ('0') AND permission.NAME='FEATURE_KMC_ENFORCE_HTTPS' ORDER BY permission.STATUS ASC LIMIT 1;" | mysql $DB1_NAME -h$DB1_HOST -u$DB1_USER -P$DB1_PORT -p$DB1_PASS 
		fi
		trap 'my_trap_handler "${LINENO}" ${$?}' ERR
	else
		DEFAULT_PORT=80
	fi
		db_input critical kaltura-front/vhost_port || true
		db_go || true
		db_get kaltura-front/vhost_port
		KALTURA_VIRTUAL_HOST_PORT=$RET

		if [ "$KALTURA_VIRTUAL_HOST_PORT" -eq 443 ];then
			PROTOCOL="https"
		else
			PROTOCOL="http"
		fi

		db_input critical kaltura-front/service_url || true
		db_go || true
		db_get kaltura-front/service_url
		SERVICE_URL=$RET



	cp $KALTURA_APACHE_CONFD/enabled.kaltura.conf.template $KALTURA_APACHE_CONFD/enabled.kaltura.conf 
	cp $KALTURA_APACHE_CONF/kaltura.conf.template $KALTURA_APACHE_CONF/kaltura.conf
	sed -e "s#@APP_DIR@#$APP_DIR#g" -e "s#@LOG_DIR@#$LOG_DIR#g" -e "s#@WEB_DIR@#$WEB_DIR#g" -e "s#@KALTURA_VIRTUAL_HOST_NAME@#$KALTURA_VIRTUAL_HOST_NAME#g" -e "s#@KALTURA_VIRTUAL_HOST_PORT@#$KALTURA_VIRTUAL_HOST_PORT#g" -e "s#@SERVICE_URL@#$SERVICE_URL#g" -i $MAIN_APACHE_CONF $KALTURA_APACHE_CONFD/enabled.kaltura.conf

	CONF_FILES=`find $APP_DIR/configurations  -type f| grep -v template`
	for i in settings.serviceUrl \$wgKalturaServiceUrl \$wgKalturaCDNUrl \$wgKalturaStatsServiceUrl apphome_url admin_console_url admin_console SERVICE_URL settings.serviceUrl; do sed -i "s#\($i\)\s*=.*#\1=$SERVICE_URL#g" $CONF_FILES;done

	a2dissite "zzzkaltura*" || true
	ln -fs $MAIN_APACHE_CONF /etc/apache2/sites-available/zzz`basename $MAIN_APACHE_CONF`
	a2ensite zzz`basename $MAIN_APACHE_CONF`

	CONFIG_CHOICES="
Please select one of the following options [0]:
0. All web interfaces 
1. Kaltura Management Console [KMC], Hosted Apps, HTML5 lib and ClipApp
2. KAC - Kaltura Admin Console
"

	db_set kaltura-front/web_interfaces "$CHOICES"
	db_get kaltura-front/web_interfaces && CONFIG_CHOICE=$RET

	find $KALTURA_APACHE_CONFD -type l -exec rm {} \;

	if [ "$CONFIG_CHOICE" = 1 ];then
		enable_apps_conf 
	elif [ "$CONFIG_CHOICE" = 2 ];then
		enable_admin_conf
	elif [ "$CONFIG_CHOICE" = 0 ];then
		enable_apps_conf
		enable_admin_conf $KALTURA_APACHE_CONFD
	else
		enable_apps_conf $KALTURA_APACHE_CONFD
		enable_admin_conf $KALTURA_APACHE_CONFD
	fi

	# cronjobs:
	ln -sf $APP_DIR/configurations/cron/api /etc/cron.d/kaltura-api
	# currently causing issues, commenting
	#ln -sf $APP_DIR/configurations/cron/cleanup /etc/cron.d/kaltura-cleanup

	# logrotate:
	ln -sf $APP_DIR/configurations/logrotate/kaltura_apache /etc/logrotate.d/ 
	ln -sf $APP_DIR/configurations/logrotate/kaltura_apps /etc/logrotate.d/

	find $BASE_DIR/app/cache/ $BASE_DIR/log -type d -exec chmod 775 {} \; 
	find $BASE_DIR/app/cache/ $BASE_DIR/log -type f -exec chmod 664 {} \; 
	chown -R $KALTURA_USER.$APACHE_USER $BASE_DIR/app/cache/ $BASE_DIR/log
	service apache2 reload
	ln -sf $BASE_DIR/app/configurations/monit/monit.avail/httpd.rc /etc/monit/conf.d/ 
	ln -sf $BASE_DIR/app/configurations/monit/monit.avail/memcached.rc /etc/monit/conf.d/
	service monit restart
		trap - ERR
		echo "use kaltura" | mysql -h$DB1_HOST -u$DB1_USER -p$DB1_PASS -P$DB1_PORT $DB1_NAME 2> /dev/null
		if [ $? -eq 0 ];then
			if [ -r $BASE_DIR/apps/studio/`rpm -qa kaltura-html5-studio --queryformat %{version}`/studio.ini ];then
				php $BASE_DIR/app/deployment/uiconf/deploy_v2.php --ini=$BASE_DIR/apps/studio/`rpm -qa kaltura-html5-studio --queryformat %{version}`/studio.ini >> /dev/null
				sed -i "s@^\(studio_version\s*=\)\(.*\)@\1 `rpm -qa kaltura-html5-studio --queryformat %{version}`@g" -i $BASE_DIR/app/configurations/local.ini
			fi
		# we can't use 'dpkg show kaltura-kmc' because this node may not be the one where we installed the KMC deb on, as it resides in the web dir and does not need to be installed on all front nodes.
			KMC_PATH=`ls -ld $BASE_DIR/web/flash/kmc/v* 2>/dev/null|awk -F " " '{print $NF}' |tail -1`
			php $BASE_DIR/app/deployment/uiconf/deploy_v2.php --ini=$KMC_PATH/config.ini >> /dev/null
			HTML5_PATH=`ls -ld $BASE_DIR/web/html5/html5lib/v* 2>/dev/null|awk -F " " '{print $NF}' |tail -1`
			sed -i "s@^\(html5_version\s*=\)\(.*\)@\1 `rpm -qa kaltura-html5lib --queryformat %{version}`@g" -i $BASE_DIR/app/configurations/local.ini
			# https://github.com/kaltura/mwEmbed/issues/574
			# find $BASE_DIR/web/html5/html5lib/ -type f -exec sed -i "s@http://cdnapi.kaltura.com@$SERVICE_URL@g" {} \;
		fi
		trap 'my_trap_handler "${LINENO}" ${$?}' ERR
		send_install_becon `basename $0` $ZONE install_success 0 

fi
