# Creates a kaltura server from a standard centos-6.5 installation
# this will always create the latest kaltura version using install scripts

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
# set this to the IP addr you wish to set on the VM host
  config.vm.network "private_network", ip: ""
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.provision "file", source: "oflaDemo-r4472-java6.war", destination: "oflaDemo-r4472-java6.war"
  config.vm.provision "file", source: "kaltura-install-config.sh", destination: "kaltura-install-config.sh"
  config.vm.provision "shell", path: "kaltura-install.sh"
end
