#!/bin/bash
set -e
if [ -n "$2" ];then
	if [ -r /etc/kaltura.d/system.ini ];then
		. /etc/kaltura.d/system.ini
		echo 'update ui_conf set html5_url = "/html5/html5lib/@@PACKAGE_VERSION@@/mwEmbedLoader.php" where html5_url like "%html5lib/v2.%" and tags like "%html5studio,player%"'|mysql -h$DB1_HOST -u $SUPER_USER -p$SUPER_USER_PASSWD -P$DB1_PORT $DB1_NAME
	fi
fi
find /opt/kaltura/web/html5/html5lib -type d -name cache -exec chown www-data {} \;
