#!/bin/bash
ldconfig
if [ "$1" = "configure" ]; then
        . /usr/share/debconf/confmodule
        db_get 'kaltura-nginx/nginx_hostname'
        if [ -z "$RET" ];then
                db_set 'kaltura-nginx/nginx_hostname' "`hostname`"
        fi
        db_input critical 'kaltura-nginx/nginx_hostname' || true
        db_go || true
        db_get 'kaltura-nginx/nginx_hostname'
        VOD_PACKAGER_HOST=$RET

        db_input critical 'kaltura-nginx/nginx_port' || true
        db_go || true
        db_get 'kaltura-nginx/nginx_port'
        VOD_PACKAGER_PORT=$RET

        db_get 'kaltura-nginx/kaltura_service_url'
        db_input critical 'kaltura-nginx/kaltura_service_url' || true
        db_go || true
        db_get 'kaltura-nginx/kaltura_service_url'
        WWW_HOST=$RET
	db_input critical kaltura-nginx/is_ssl || true
	db_go || true
	db_get kaltura-nginx/is_ssl
	IS_NGINX_SSL="$RET"
	if [ "$IS_NGINX_SSL" = 'true' ];then
		db_input critical 'kaltura-nginx/nginx_ssl_port' || true
		db_go || true
		db_get 'kaltura-nginx/nginx_ssl_port'
		VOD_PACKAGER_SSL_PORT=$RET

		db_input critical 'kaltura-nginx/ssl_cert' || true
		db_go || true
		db_get 'kaltura-nginx/ssl_cert'
		SSL_CERT=$RET

		db_input critical 'kaltura-nginx/ssl_key' || true
		db_go || true
		db_get 'kaltura-nginx/ssl_key'
		SSL_KEY=$RET
		sed -e "s#@VOD_PACKAGER_HOST@#$VOD_PACKAGER_HOST#g" -e "s#@VOD_PACKAGER_SSL_PORT@#$VOD_PACKAGER_SSL_PORT#g" -e "s#@SSL_CERT@#$SSL_CERT#g" -e "s#@SSL_KEY@#$SSL_KEY#g" /opt/kaltura/nginx/conf/ssl.conf.template > /opt/kaltura/nginx/conf/ssl.conf
	else
		touch /opt/kaltura/nginx/conf/ssl.conf
	fi
        sed -e "s#@VOD_PACKAGER_HOST@#$VOD_PACKAGER_HOST#g" -e "s#@VOD_PACKAGER_PORT@#$VOD_PACKAGER_PORT#g" -e "s#@LOG_DIR@#/opt/kaltura/log/nginx#" -e "s#@WWW_HOST@#$WWW_HOST#g" /opt/kaltura/nginx/conf/nginx.conf.template > /opt/kaltura/nginx/conf/nginx.conf
	sed -e 's#@STATIC_FILES_PATH@#/opt/kaltura/nginx/static#g' /opt/kaltura/nginx/conf/kaltura.conf.template > /opt/kaltura/nginx/conf/kaltura.conf
        update-rc.d kaltura-nginx defaults || true

fi
KALTURA_FUNCTIONS_RC=/opt/kaltura/bin/kaltura-functions.rc
if [ ! -r "$KALTURA_FUNCTIONS_RC" ];then
        OUT="${BRIGHT_RED}ERROR:could not find $KALTURA_FUNCTIONS_RC so, exiting..${NORMAL}"
        echo -en $OUT
        exit 3
fi


. $KALTURA_FUNCTIONS_RC
if [ -r $CONSENT_FILE ];then
        . $CONSENT_FILE
fi

#ln -sf $BASE_DIR/app/configurations/logrotate/kaltura_populate /etc/logrotate.d/
trap 'my_trap_handler "${LINENO}" ${$?}' ERR
chown -R kaltura /opt/kaltura/log/nginx
service kaltura-nginx reload 
