#! /bin/sh
set -e

if test "$1" = "purge"; then
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/php5/mods-available/ssh2.ini
    fi
    rm -f /etc/php5/mods-available/ssh2.ini
fi

#DEBHELPER#

exit 0
