#!/bin/sh

set -e



[ "$1" = "configure" ] && ldconfig

if [ "$1" != "configure" ]; then
    exit 0
fi

phpini="/opt/kaltura/app/configurations/php/embed/php.ini"

ucf /usr/share/php5/php.ini-production $phpini
ucfr libphp5-embed $phpini

exit 0
