<?php
if ($argc < 7 ) {
	echo 'Usage: ' . __FILE__ . ' <service_url> <partner_id> <partner_secret> <FTP|SFTP|SCP|S3> <storage_display_name> <storage_url> <storage_base_dir> <delivery_url> <username> <passwd> <storage_type>'."\n";
	exit (1);
}
require_once('/opt/kaltura/web/content/clientlibs/php5/KalturaClient.php');

$protocols['FTP'] = KalturaStorageProfileProtocol::FTP;
$protocols['SFTP'] = KalturaStorageProfileProtocol::SFTP;
$protocols['SCP'] = KalturaStorageProfileProtocol::SCP;
$protocols['S3'] = KalturaStorageProfileProtocol::S3;

$storage_type['akamai']= 0;
$storage_type['s3']= 1;

$service_url=$argv[1];
$partner_id=$argv[2];
$minus2_secret=$argv[3];
$protocol=$argv[4];
$storage_display_name=$argv[5];
$storage_url=$argv[6];
$storage_base_dir=$argv[7];
$delivery_url=$argv[8];
$username=$argv[9];
$passwd=$argv[10];
$storage_type=$argv[11];
$config = new KalturaConfiguration($partner_id);
$config->serviceUrl = $service_url;
$client = new KalturaClient($config);
$user_id=null;
$expiry=null;
$privileges=null;
$type = KalturaSessionType::ADMIN;
$ks = $client->session->start($minus2_secret, null, $type, -2, $expiry, $privileges);
$client->setKs($ks);
$config->partnerId=$partner_id;
$client->setConfig($config);
$storageProfile = new KalturaStorageProfile();
$storageProfile->name = $storage_display_name;
$storageProfile->systemName = $storage_display_name;
$storageProfile->desciption = $storage_display_name.' - auto generated by '. __FILE__."\n";
$storageProfile->status = KalturaStorageProfileStatus::AUTOMATIC;
$storageProfile->protocol = $protocols[$protocol];
$storageProfile->storageUrl = $storage_url;
$storageProfile->storageBaseDir = $storage_base_dir;
$storageProfile->storageUsername = $username;
$storageProfile->storagePassword = $passwd;
if (preg_match('#^https://#',$delivery_url)){
	$storageProfile->deliveryHttpsBaseUrl = $delivery_url;
}else{
	$storageProfile->deliveryHttpBaseUrl = $delivery_url;
}
$storageProfile->deliveryRmpBaseUrl = null;
$storageProfile->flavorParamsIds = 0;
//$storageProfile->urlManagerClass = 'MANAGER_CLASS';
$storageProfile->urlManagerParams = array();
$storageProfile->urlManagerParams[0] = null;
$storageProfile->readyBehavior = null;
$result = $client->storageProfile->add($storageProfile);
?>
