#!/bin/bash
KALTURA_GROUP=kaltura
KALTURA_USER=kaltura
KALTURA_PREFIX=/opt/kaltura
PLAYKIT_PREFIX=$KALTURA_PREFIX/playkit-js-bundle-builder
if [ "$1" = "configure" ]; then
        update-rc.d kaltura-playkit-bundler defaults || true
fi
mkdir -p $KALTURA_PREFIX/.forever
chown -R $KALTURA_USER:$KALTURA_GROUP $PLAYKIT_PREFIX/log $PLAYKIT_PREFIX/var/run $KALTURA_PREFIX/.forever
cd $PLAYKIT_PREFIX && npm install && npm install -g gulp forever
# package.json has ^3.4.0 and it doesn't work
rm -rf node_modules/uuid
npm install uuid@^3.1 --save-dev

if [ -r $KALTURA_PREFIX/app/configurations/local.ini ];then
	SALT=`grep remote_addr_header_salt $KALTURA_PREFIX/app/configurations/local.ini|sed 's@^remote_addr_header_salt\s*=\s*\(.*\)$@\1@g'| sed 's@"@@g'`
	sed -i "s#@APP_REMOTE_ADDR_HEADER_SALT@#$SALT#g" $PLAYKIT_PREFIX/config/default.json
	invoke-rc.d kaltura-playkit-bundler restart
fi
